<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">NETSUITE OP</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
</nav>

<br>

<!--<div class="container-fluid">
	<form role="form">
		<div class="form-row align-items-center">-->
		
			<!--ZONA QUE NO VA-->
			<!-- <div class="col-auto">
				<label class="sr-only" for="fec_ini">Fecha Inicial</label>
				<input type="date" class="form-control" id="fec-ini" placeholder="dd/mm/aaaa">
			</div>
			<div class="col-auto">
				<label class="sr-only" for="fec_fin">Fecha Final</label>
				<input type="date" class="form-control" id="fec-fin" placeholder="dd/mm/aaaa">
			</div>-->
			<!--ZONA QUE NO VA-->
			
			<!--<div class="col-auto">
				<label class="sr-only" for="num-op">N&uacute;mero de gu&iacute;a</label>
				<input type="text" class="form-control only-number" id="num-op" placeholder="Orden de Producción">
			</div>
			<div class="colauto">
				<button type="button" id="btn-filtrar" class="btn btn-primary"></button>
			</div>
		</div>
	</form>
	<br>
	<div class="table-responsive" style="overflow-x:auto;width: 100%;border-collapse:collapse;">
		<table id="tb_OP" class="table table-striped table-bordered table-hover">
			<thead class="head">
			</thead>
			<tbody class="body">
			</tbody>
		</table>
	</div>
	<div class="text-center">
		<div class="total"></div>
		<div class="paginate"></div>
	</div>
</div>-->